version: 2
# CircleCI integration with Drupal 8.

## Defines images and working directory.
defaults: &defaults
  docker:
    - image: pookmish/drupal8ci:pcov
    - image: selenium/standalone-chrome:latest
    - image: mariadb:10.3
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
  working_directory: /var/www/html

#Jobs
code_coverage: &code_coverage
  <<: *defaults
  steps:
    - restore_cache:
        keys:
          - dependencies-v1
    - checkout:
        path: /var/www/test
    - run:
        name: Run PHP Unit Coverage Tests
        command: |
          composer global require SU-SWS/stanford-caravan:dev-8.x-2.x
          ~/.composer/vendor/bin/sws-caravan phpunit /var/www/html --extension-dir=/var/www/test --with-coverage
    - save_cache:
        key: dependencies-v1-{{ epoch }}
        paths:
          - .
    - store_test_results:
        path: /var/www/html/artifacts/phpunit
    - store_artifacts:
        path: /var/www/html/artifacts/phpunit/coverage

back_to_dev: &back_to_dev
  <<: *defaults
  steps:
    - checkout
    - run:
        name: Back to dev
        command: |
          composer global require SU-SWS/stanford-caravan:dev-8.x-2.x
          ~/.composer/vendor/bin/sws-caravan back-to-dev ${CIRCLE_TAG} ${CIRCLE_WORKING_DIRECTORY}

d8_codeception: &d8_codeception
  <<: *defaults
  steps:
    - checkout:
        path: /var/www/test
    - run:
        name: Run Codeception Tests
        command: |
          composer global require SU-SWS/stanford-caravan:dev-8.x-1.x
          ~/.composer/vendor/bin/sws-caravan codeception /var/www/html --extension-dir=/var/www/test
    - store_test_results:
        path: /var/www/html/artifacts/behat
    - store_artifacts:
        path: /var/www/html/artifacts

d9_codeception: &d9_codeception
  <<: *defaults
  steps:
    - checkout:
        path: /var/www/test
    - run:
        name: Run Codeception Tests
        command: |
          composer global require SU-SWS/stanford-caravan:dev-8.x-2.x
          ~/.composer/vendor/bin/sws-caravan codeception /var/www/html --extension-dir=/var/www/test
    - store_test_results:
        path: /var/www/html/artifacts/behat
    - store_artifacts:
        path: /var/www/html/artifacts

# Declare all of the jobs we should run.
jobs:
  run-coverage:
    <<: *code_coverage
  run-back-to-dev:
    <<: *back_to_dev
  run-d8-codeception:
    <<: *d8_codeception
  run-d9-codeception:
    <<: *d9_codeception

# Declare a workflow that runs all of our jobs in parallel.
workflows:
  version: 2
  after_release:
    jobs:
      - run-back-to-dev:
          filters:
            tags:
              only:
                - /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*?$/
            branches:
              ignore:
                - /.*/
  tests:
    jobs:
      - run-coverage
      - run-d8-codeception
      - run-d9-codeception
  # Re-test every sunday in case this code becomes stale.
  sundays:
    jobs:
      - run-coverage
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - 8.x-1.x
